// styles/HomeScreenStyles.js
import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    backgroundGradient: {
        flex: 1,
        width: '100%',
        height: '100%',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 15,
        backgroundColor: 'rgba(10, 36, 114, 0.8)',
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#fff',
    },
    notificationIcon: {
        padding: 8,
    },
    searchContainer: {
        flexGrow: 1,
        padding: 20,
        flexDirection: 'column',
        paddingBottom: 100,
    },
    inputContainer: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        borderRadius: 12,
        padding: 15,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    inputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
    },
    inputIcon: {
        marginRight: 10,
    },
    input: {
        flex: 1,
        fontSize: 16,
        color: '#333',
        paddingVertical: 8,
    },
    inputDivider: {
        height: 1,
        backgroundColor: '#E0E0E0',
        marginVertical: 8,
    },
    suggestionsContainer: {
        backgroundColor: 'white',
        borderRadius: 8,
        marginTop: 4,
        maxHeight: 200,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    suggestionItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    suggestionIcon: {
        marginRight: 10,
    },
    suggestionText: {
        fontSize: 16,
        color: '#333',
    },
    findButton: {
        backgroundColor: '#0a2472',
        paddingVertical: 15,
        borderRadius: 12,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    findButtonDisabled: {
        backgroundColor: 'rgba(10, 36, 114, 0.7)',
    },
    findButtonText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    frequentSearchesContainer: {
        marginTop: 20,
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        borderRadius: 12,
        padding: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    frequentSearchesTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 15,
    },
    frequentSearchesIcon: {
        marginRight: 8,
    },
    frequentSearchesTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#0a2472',
    },
    frequentSearchesGrid: {
        flexDirection: 'column',
        gap: 10,
    },
    frequentSearchItem: {
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
        padding: 12,
        width: '100%',
        marginBottom: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 4,
        borderWidth: 1,
        borderColor: 'rgba(10, 36, 114, 0.2)',
    },
    frequentSearchContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    frequentSearchLocation: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    frequentSearchIcon: {
        marginRight: 6,
    },
    frequentSearchFrom: {
        fontSize: 15,
        color: '#0a2472',
        flex: 1,
        fontWeight: '500',
    },
    frequentSearchTo: {
        fontSize: 15,
        color: '#0a2472',
        flex: 1,
        fontWeight: '500',
    },
    bottomNav: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        paddingVertical: 12,
        backgroundColor: '#fff',
        borderTopWidth: 1,
        borderTopColor: '#eee',
    },
    navItem: {
        alignItems: 'center',
        paddingHorizontal: 10,
    },
    navText: {
        fontSize: 12,
        marginTop: 4,
    },
    iosButtonText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    iosButton: {
        backgroundColor: '#0a2472',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 10,
        marginBottom: 20,
    },
    pickerContainer: {
        backgroundColor: '#333', // Dark background for the picker
        borderRadius: Platform.OS === 'ios' ? 10 : 0,
        padding: Platform.OS === 'ios' ? 10 : 0,
        margin: 10,
        height: Platform.OS === 'ios' ? 200 : 'auto',
    },
    buttonContainer: {
        margin: 10,
    },
    dateTimeInput: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingRight: 12,
    },
    dateTimeText: {
        fontSize: 16,
        color: '#000',
    },
    privateRidesContainer: {
        marginTop: 20,
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        borderRadius: 12,
        padding: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        marginBottom: Platform.OS === 'ios' ? 40 : 20,
    },
    privateRidesHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 6,
    },
    privateRidesIcon: {
        marginRight: 10,
    },
    privateRidesTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#0a2472',
    },
    privateRidesDescription: {
        fontSize: 13,
        color: '#666',
        marginBottom: 12,
        lineHeight: 18,
    },
    privateRidesButton: {
        backgroundColor: '#0a2472',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 8,
        alignItems: 'center',
    },
    privateRidesButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
});